# Generated by Django 5.2.18 on 2026-10-08 12:46

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.CharField(db_column='maphongban', max_length=10, primary_key=True, serialize=False, verbose_name='Mã phòng ban')),
                ('name', models.CharField(db_column='tenphongban', max_length=100, unique=True, verbose_name='Tên phòng ban')),
                ('description', models.TextField(blank=True, db_column='mota', verbose_name='Mô tả')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='ngaytao')),
            ],
            options={
                'verbose_name': 'Phòng ban',
                'verbose_name_plural': 'Phòng ban',
                'db_table': 'PHONGBAN',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.CharField(db_column='manv', editable=False, max_length=10, primary_key=True, serialize=False, verbose_name='Mã nhân viên')),
                ('name', models.CharField(db_column='tennv', max_length=100, verbose_name='Họ và tên')),
                ('birth_date', models.DateField(blank=True, db_column='ngaysinh', null=True, verbose_name='Ngày sinh')),
                ('gender', models.CharField(choices=[('Nam', 'Nam'), ('Nữ', 'Nữ')], db_column='gioitinh', max_length=3, verbose_name='Giới tính')),
                ('phone', models.CharField(db_column='sdt', max_length=10, unique=True, validators=[django.core.validators.RegexValidator('\\A0[0-9]{9}\\Z', 'Số điện thoại phải gồm 10 chữ số, bắt đầu bằng 0.')], verbose_name='Số điện thoại')),
                ('email', models.EmailField(db_column='email', max_length=254, unique=True, verbose_name='Email')),
                ('identity', models.CharField(db_column='cccd', max_length=12, unique=True, validators=[django.core.validators.RegexValidator('\\A[0-9]{12}\\Z', 'CCCD phải gồm đúng 12 chữ số.')], verbose_name='CCCD')),
                ('address', models.CharField(blank=True, db_column='diachi', max_length=255, verbose_name='Địa chỉ')),
                ('job', models.CharField(db_column='chucvu', max_length=100, verbose_name='Chức vụ')),
                ('start_date', models.DateField(db_column='ngayvaolam', verbose_name='Ngày vào làm')),
                ('is_active', models.BooleanField(db_column='trangthai', default=True, verbose_name='Đang làm việc')),
                ('end_date', models.DateField(blank=True, db_column='ngaynghiviec', null=True, verbose_name='Ngày nghỉ việc')),
                ('reason', models.TextField(blank=True, db_column='lydonghiviec', verbose_name='Lý do nghỉ việc')),
                ('department', models.ForeignKey(db_column='maphong', on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='employees.department', verbose_name='Phòng ban')),
                ('user', models.OneToOneField(blank=True, db_column='id_taikhoan', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employee', to=settings.AUTH_USER_MODEL, verbose_name='Tài khoản')),
            ],
            options={
                'verbose_name': 'Nhân viên',
                'verbose_name_plural': 'Nhân viên',
                'db_table': 'NHANVIEN',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.CharField(db_column='mahd', editable=False, max_length=10, primary_key=True, serialize=False, verbose_name='Mã hợp đồng')),
                ('type', models.CharField(choices=[('THU_VIEC', 'Thử việc'), ('XAC_DINH_1_NAM', 'Xác định thời hạn 1 năm'), ('KHONG_XAC_DINH', 'Không xác định thời hạn')], db_column='loaihd', max_length=30, verbose_name='Loại hợp đồng')),
                ('signed_date', models.DateField(db_column='ngayky', verbose_name='Ngày ký')),
                ('start_date', models.DateField(db_column='ngaybatdau', verbose_name='Ngày bắt đầu')),
                ('end_date', models.DateField(blank=True, db_column='ngayhethan', null=True, verbose_name='Ngày hết hạn')),
                ('salary', models.DecimalField(db_column='luongcoban', decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Lương cơ bản')),
                ('renewal_date', models.DateField(blank=True, db_column='ngaygiahan', null=True, verbose_name='Ngày gia hạn')),
                ('status', models.CharField(choices=[('CHUHIEULUC', 'Chưa hiệu lực'), ('DANGHIEULUC', 'Đang hiệu lực'), ('HETHAN', 'Hết hạn'), ('CHAMDUT', 'Chấm dứt')], db_column='trangthai', default='CHUHIEULUC', max_length=20, verbose_name='Trạng thái')),
                ('employee', models.ForeignKey(db_column='manv', on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='employees.employee', verbose_name='Nhân viên')),
            ],
            options={
                'verbose_name': 'Hợp đồng',
                'verbose_name_plural': 'Hợp đồng',
                'db_table': 'HOPDONG',
                'ordering': ['id'],
            },
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('email'), name='employee_email_case_insensitive'),
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__isnull', True), ('end_date__gte', models.F('start_date')), _connector='OR'), name='employee_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('end_date__isnull', True), ('is_active', True), ('reason', '')), models.Q(('end_date__isnull', False), ('is_active', False), models.Q(('reason', ''), _negated=True)), _connector='OR'), name='employee_departure_required'),
        ),
        migrations.AddConstraint(
            model_name='contract',
            constraint=models.CheckConstraint(condition=models.Q(('salary__gte', Decimal('0.01'))), name='contract_positive_salary'),
        ),
        migrations.AddConstraint(
            model_name='contract',
            constraint=models.CheckConstraint(condition=models.Q(('signed_date__lte', models.F('start_date'))), name='contract_sign_before_start'),
        ),
        migrations.AddConstraint(
            model_name='contract',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('end_date__isnull', True), ('type', 'KHONG_XAC_DINH')), models.Q(models.Q(('type', 'KHONG_XAC_DINH'), _negated=True), ('end_date__gt', models.F('start_date'))), _connector='OR'), name='contract_valid_end_date'),
        ),
    ]
