# Generated by Django 5.2.18 on 2026-10-08 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_departments'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='contract',
            name='contract_valid_end_date',
        ),
        migrations.AddConstraint(
            model_name='contract',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('end_date__isnull', True), ('type', 'KHONG_XAC_DINH')), models.Q(models.Q(('type', 'KHONG_XAC_DINH'), _negated=True), ('end_date__gt', models.F('start_date')), ('end_date__isnull', False)), _connector='OR'), name='contract_valid_end_date'),
        ),
    ]
